server_name: matrix.astrid.tech
pid_file: /data/homeserver.pid
listeners:
  - port: 80
    tls: false
    type: http
    x_forwarded: true
    resources:
      - names:
          - client
          - federation
        compress: false
limit_remote_rooms: null
retention: null
caches:
  per_cache_factors: null
log_config: /data/log.config
media_store_path: /data/media_store
signing_key_path: /data/signing.key
url_preview_accept_language: null
account_validity: null
account_threepid_delegates: null
metrics_flags: null
report_stats: true
old_signing_keys: null
trusted_key_servers:
  - server_name: matrix.org
saml2_config:
  sp_config: null
  user_mapping_provider:
    config: null
oidc_providers: null
cas_config: null
sso: null
password_config:
  policy: null
ui_auth: null
email: null
password_providers: null
push: null
spam_checker: null
user_directory: null
stats: null
opentracing: null
redis: null
