all:
  hosts:
    cracktop.p.astrid.tech:
      ansible_host: 192.168.8.41
      ansible_user: root
    thonkpad.p.astrid.tech:
      ansible_host: 192.168.8.42
      ansible_user: root
    badtop.p.astrid.tech:
      ansible_host: 192.168.8.43
      ansible_user: root
    optipoop.p.astrid.tech:
      ansible_host: 192.168.8.40
      ansible_user: root

    ipa0.p.astrid.tech:
      ansible_host: 192.168.8.9
      ansible_user: astrid

    sambruh.p.astrid.tech:
      ansible_user: root

    mysql0.p.astrid.tech:
      ansible_user: root

    cracktop-kube.p.astrid.tech:
      ansible_user: astrid
    thonkpad-kube.p.astrid.tech:
      ansible_user: astrid
    badtop-kube.p.astrid.tech:
      ansible_user: astrid
    zerg[00:01].p.astrid.tech:
      ansible_user: ubuntu
    zerg02.p.astrid.tech:
      ansible_user: pi
    zerg03.p.astrid.tech:
      ansible_user: root

proxmox:
  hosts:
    cracktop.p.astrid.tech:
      pve_kube_node: cracktop
      pve_kube_index: 0
      pve_kube_cores: 4
      pve_kube_memory: 7168
      pve_kube_memory_min: 1024
    thonkpad.p.astrid.tech:
      pve_kube_node: thonkpad
      pve_kube_index: 1
      pve_kube_cores: 4
      pve_kube_memory: 7168
      pve_kube_memory_min: 1024
    badtop.p.astrid.tech:
      pve_kube_node: badtop
      pve_kube_index: 2
      pve_kube_cores: 4
      pve_kube_memory: 3072
      pve_kube_memory_min: 1024
    optipoop.p.astrid.tech:

turnkey:
  hosts:
    sambruh.p.astrid.tech:

laptop:
  hosts:
    cracktop.p.astrid.tech:
    thonkpad.p.astrid.tech:
    badtop.p.astrid.tech:

ipaserver:
  hosts:
    ipa0.p.astrid.tech:
  vars:
    ipaserver_install_packages: no
    ipaserver_domain: astrid.tech
    ipaserver_realm: ASTRID.TECH
    ipaserver_setup_dns: yes
    ipaserver_auto_forwarders: yes

ipareplicas:
  hosts:
    ipa1.p.astrid.tech:

pkg_apt:
  hosts:
    cracktop.p.astrid.tech:
    thonkpad.p.astrid.tech:
    badtop.p.astrid.tech:
    optipoop.p.astrid.tech:
    sambruh.p.astrid.tech:
    cracktop-kube.p.astrid.tech:
    thonkpad-kube.p.astrid.tech:
    badtop-kube.p.astrid.tech:
    zerg[00:03].p.astrid.tech:

pkg_dnf:
  hosts:
    ipa0.p.astrid.tech:
    ipa1.p.astrid.tech:

kubernetes:
  children:
    kubernetes_home_0:
      hosts:
        cracktop-kube.p.astrid.tech:
          kube_labels:
            - k8s.astrid.tech/storage-type=ssd
            - node.kubernetes.io/instance-type=laptop.mid
        thonkpad-kube.p.astrid.tech:
          kube_labels:
            - k8s.astrid.tech/storage-type=ssd
            - node.kubernetes.io/instance-type=laptop.mid
        badtop-kube.p.astrid.tech:
          kube_labels:
            - k8s.astrid.tech/storage-type=hdd
            - node.kubernetes.io/instance-type=laptop.low
        zerg[00:03].p.astrid.tech:
          kube_labels:
            - k8s.astrid.tech/storage-type=sd-card
            - node.kubernetes.io/instance-type=soc.low
      vars:
        kube_labels:
          - topology.kubernetes.io/region=us-norcal
          - topology.kubernetes.io/zone=home-0
    kubernetes_master:
      hosts:
        cracktop-kube.p.astrid.tech:
        thonkpad-kube.p.astrid.tech:
    kubernetes_agent:
      hosts:
        badtop-kube.p.astrid.tech:
        zerg[00:03].p.astrid.tech:
